export const GET_TODOLISTS_EPIC = 'GET_TODOLISTS_EPIC';
export const GET_TODOLISTS_LOADING = 'GET_TODOLISTS_LOADING';
export const GET_TODOLISTS_SUCCESS = 'GET_TODOLISTS_SUCCESS';
export const GET_TODOLISTS_ERROR = 'GET_TODOLISTS_ERROR';
export const GET_TODOLISTS_CANCEL = 'GET_TODOLISTS_CANCEL';
