export const GET_COMMENTS_EPIC = 'GET_COMMENTS_EPIC';
export const GET_COMMENTS_LOADING = 'GET_COMMENTS_LOADING';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';
export const GET_COMMENTS_CANCEL = 'GET_COMMENTS_CANCEL';
